CREATE TABLE user(
user_ID INT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(50) NOT NULL UNIQUE,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
phone VARCHAR(10) NOT NULL,
password VARCHAR(255) NOT NULL,
state CHAR(2) NOT NULL,
city VARCHAR(30) NOT NULL,
zipcode VARCHAR(5) NOT NULL,
street VARCHAR(50) NOT NULL
);

CREATE TABLE area(
area_ID INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(60) NOT NULL UNIQUE,
state CHAR(2) NOT NULL,
county VARCHAR(30) NOT NULL,
city VARCHAR(30) NOT NULL,
street_address VARCHAR(30) NOT NULL UNIQUE,
zipcode VARCHAR(5) NOT NULL
);

CREATE TABLE site(
site_ID INT PRIMARY KEY AUTO_INCREMENT,
timestamp DATE NOT NULL,
note VARCHAR(250) NOT NULL,
electrical TINYINT NOT NULL,
restrooms TINYINT NOT NULL,
shower TINYINT NOT NULL,
nightly_fee DECIMAL(5,2) NOT NULL,
latitude DECIMAL(10,7) NOT NULL,
longitude DECIMAL(10,7) NOT NULL,
area_ID int NOT NULL,
creator_ID int NOT NULL,
CONSTRAINT site_fk_area FOREIGN KEY (area_ID) REFERENCES area(area_ID),
CONSTRAINT site_fk_user FOREIGN KEY (creator_ID) REFERENCES user(user_ID)
);

CREATE TABLE IF NOT EXISTS liked_user_site(
user_ID INT NOT NULL,
site_ID INT NOT NULL,
PRIMARY KEY (user_ID, site_ID),
CONSTRAINT liked_user_site_fk_user FOREIGN KEY (user_ID) REFERENCES user(user_ID),
CONSTRAINT liked_user_site_fk_site FOREIGN KEY (site_ID) REFERENCES site(site_ID)
);

CREATE TABLE IF NOT EXISTS rule(
rule_ID INT PRIMARY KEY AUTO_INCREMENT,
rule varchar(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS site_rule(
rule_ID INT NOT NULL,
site_ID INT NOT NULL,
PRIMARY KEY (rule_ID, site_ID),
CONSTRAINT site_rule_fk_user FOREIGN KEY (rule_ID) REFERENCES rule(rule_ID),
CONSTRAINT site_rule_fk_site FOREIGN KEY (site_ID) REFERENCES site(site_ID)
);

CREATE TABLE rating(
rating_ID INT PRIMARY KEY AUTO_INCREMENT,
cleanliness INT NOT NULL,
accessibility INT NOT NULL,
quietness INT NOT NULL,
activities INT NOT NULL,
amenities INT NOT NULL,
cost INT NOT NULL,
site_ID INT NOT NULL,
CONSTRAINT rating_check_max CHECK(
cleanliness BETWEEN 1 AND 10 AND
accessibility BETWEEN 1 AND 10 AND
quietness BETWEEN 1 AND 10 AND
activities BETWEEN 1 AND 10 AND
amenities BETWEEN 1 AND 10 AND
cost BETWEEN 1 AND 10),
CONSTRAINT rating_fk_site FOREIGN KEY (site_ID) REFERENCES site(site_ID)
);

CREATE TABLE photo(
photo_ID INT PRIMARY KEY AUTO_INCREMENT,
filepath VARCHAR(250) NOT NULL,
site_ID INT NOT NULL,
CONSTRAINT photo_fk_site FOREIGN KEY (site_ID) REFERENCES site(site_ID)
);

CREATE TABLE comment(
comment_ID INT PRIMARY KEY AUTO_INCREMENT,
comment VARCHAR(250) NOT NULL,
timestamp DATE NOT NULL,
site_ID INT NOT NULL,
user_ID INT NOT NULL,
CONSTRAINT comment_fk_site FOREIGN KEY (site_ID) REFERENCES site(site_ID),
CONSTRAINT comment_fk_user FOREIGN KEY (user_ID) REFERENCES user(user_ID)
);



