USE group1;


DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS photo;
DROP TABLE IF EXISTS rating;
DROP TABLE IF EXISTS site_rule;
DROP TABLE IF EXISTS liked_user_site;
DROP TABLE IF EXISTS site;

DROP TABLE IF EXISTS rule;
DROP TABLE IF EXISTS area;
DROP TABLE IF EXISTS user;
