



INSERT INTO photo (site_ID, filepath)
VALUES 
(1, './static/campsite_photos/template.jfif'),
(2, './static/campsite_photos/template.jfif'),
(3, './static/campsite_photos/template.jfif'),
(4, './static/campsite_photos/template.jfif'),
(5, './static/campsite_photos/template.jfif'),
(6, './static/campsite_photos/template.jfif'),
(7, './static/campsite_photos/template.jfif'),
(8, './static/campsite_photos/template.jfif'),
(9, './static/campsite_photos/template.jfif'),
(10, './static/campsite_photos/template.jfif'),
(11, './static/campsite_photos/template.jfif'),
(12, './static/campsite_photos/template.jfif'),
(13, './static/campsite_photos/template.jfif'),
(14, './static/campsite_photos/template.jfif'),
(15, './static/campsite_photos/template.jfif'),
(16, './static/campsite_photos/template.jfif'),
(17, './static/campsite_photos/template.jfif'),
(18, './static/campsite_photos/template.jfif'),
(19, './static/campsite_photos/template.jfif'),
(20, './static/campsite_photos/template.jfif'),
(21, './static/campsite_photos/template.jfif'),
(22, './static/campsite_photos/template.jfif'),
(23, './static/campsite_photos/template.jfif'),
(24, './static/campsite_photos/template.jfif'),
(25, './static/campsite_photos/template.jfif'),
(26, './static/campsite_photos/template.jfif'),
(27, './static/campsite_photos/template.jfif'),
(28, './static/campsite_photos/template.jfif'),
(29, './static/campsite_photos/template.jfif'),
(30, './static/campsite_photos/template.jfif'),
(31, './static/campsite_photos/template.jfif'),
(32, './static/campsite_photos/template.jfif'),
(33, './static/campsite_photos/template.jfif'),
(34, './static/campsite_photos/template.jfif'),
(35, './static/campsite_photos/template.jfif'),
(36, './static/campsite_photos/template.jfif'),
(37, './static/campsite_photos/template.jfif'),
(38, './static/campsite_photos/template.jfif'),
(39, './static/campsite_photos/template.jfif'),
(40, './static/campsite_photos/template.jfif');